### ISSUE TITLE
Document the naming convention and the directory structure to be used for Dockerfiles

### ISSUE THREAD

**Issue by gupta-utkarsh** [Cloud-CV/Dockerfiles#3]

**Comment by fristonio** [comment]
Cool, I will document the whole thing and add it to Wiki. :)

**Comment by fristonio** [comment]
[Here](https://github.com/Cloud-CV/Dockerfiles/wiki/Dockerfiles-Structure) is the initial design I have in mind for this. If you have any comments or suggestions, pass it on to the wiki.
@deshraj @AvaisP @uttu357

**Comment by fristonio** [comment]
WIKI Link for the design - https://github.com/Cloud-CV/Dockerfiles/wiki/Dockerfiles-Structure
